from datetime import date, datetime, timezone
from typing import List, Optional

from sqlalchemy import Date, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.extensions import db
from app.models.associations import visual_tags
from app.models.enums import Context, Origin, Status, ThemeAffinity, VisualKind, as_sa_enum


class Visual(db.Model):
    __tablename__ = "visuals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    slug: Mapped[str] = mapped_column(String(140), unique=True, index=True, nullable=False)
    title: Mapped[str] = mapped_column(String(160), nullable=False)
    kind: Mapped[VisualKind] = mapped_column(as_sa_enum(VisualKind), index=True, nullable=False)
    source: Mapped[str] = mapped_column(Text, nullable=False, default="")
    asset_path: Mapped[Optional[str]] = mapped_column(String(300), nullable=True)
    theme_affinity: Mapped[ThemeAffinity] = mapped_column(
        as_sa_enum(ThemeAffinity), nullable=False, default=ThemeAffinity.ADAPTIVE
    )
    origin: Mapped[Origin] = mapped_column(as_sa_enum(Origin), nullable=False, default=Origin.HUMAN)
    generator: Mapped[Optional[str]] = mapped_column(String(80), nullable=True)
    created_on: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    context: Mapped[Context] = mapped_column(as_sa_enum(Context), nullable=False, default=Context.PERSONAL)
    course: Mapped[Optional[str]] = mapped_column(String(60), nullable=True)
    summary_md: Mapped[str] = mapped_column(Text, nullable=False, default="")
    notes_md: Mapped[str] = mapped_column(Text, nullable=False, default="")
    status: Mapped[Status] = mapped_column(as_sa_enum(Status), index=True, nullable=False, default=Status.PENDING)
    category_id: Mapped[int] = mapped_column(ForeignKey("categories.id"), index=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    category: Mapped["Category"] = relationship(back_populates="visuals")
    tags: Mapped[List["Tag"]] = relationship(secondary=visual_tags, back_populates="visuals")
    resources: Mapped[List["Resource"]] = relationship(back_populates="visual", cascade="all, delete-orphan")

    @property
    def needs_sandbox(self) -> bool:
        return self.kind in VisualKind.code_bearing()

    @property
    def attribution(self) -> str:
        if self.origin == Origin.MACHINE:
            return f"Generated by {self.generator}" if self.generator else "Machine-generated"
        if self.origin == Origin.HYBRID:
            return f"{self.generator}, edited by hand" if self.generator else "Machine-generated, edited by hand"
        return "Hand-authored"
